ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
ERROR:root:An error occurred in file 'test.py', line 262: Result is not set.
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in main_controller
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/LISTING_SCREENER_S_BOT/test.py", line 237, in <listcomp>
    sell_orders_list = [task for task in sell_controller_tasks if task.result()][0]
                                                                  ^^^^^^^^^^^^^
asyncio.exceptions.InvalidStateError: Result is not set.
